config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, controllers: {registrations: 'registrations'}, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index
  
  scope :admin do

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :payments do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :road_transports do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end

    resources :municipalities do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :sectors do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :terms do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :riffils_centers do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end
    
  end

  #ajax galeria
  get '/option-landing-gallery/:option', to: 'frontend#option_landing_gallery', as: :option_landing_gallery
  get '/option-show-gallery/:option', to: 'frontend#option_show_gallery', as: :option_show_gallery


  #galeria show
  get '/gallery/:option', to: 'frontend#show_gallery', as: :show_gallery

  #orders
  get '/ordenes', to: 'orders#view_orders', as: :view_orders
  post '/ordenes/new_order', to: 'orders#create_orders', as: :create_orders

  #orders edit status admin
  put '/ordenes/change_status/:id', to: 'orders#change_status', as: :change_status

  #mail
  get '/ordenes/send_receipt/:id', to: 'orders#send_receipt', as: :send_receipt

  #Mercado_Pago
  get '/ordenes/success', to: 'mercado_pago#success', as: :success
  get '/ordenes/failure', to: 'mercado_pago#failure', as: :failure
  post '/ordenes/hook', to: 'mercado_pago#hook', as: :hook

  #validar mercado pago ordenes
  get '/validate_payment/:id', to: 'orders#validate_payment', as: :validate_payment

  #user edit
  get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
  put '/users/update_user_edit/:id', to: 'users#update_user_edit', as: :update_user_edit

  #export user
  get '/export/user', to: 'users#export', as: :export_user

  get '/get-sectors/:opcion/:municipality_id', to: 'frontend#get_sectors', as: :get_sectors
  get '/get-center/:opcion/:center_id', to: 'frontend#get_center', as: :get_road
  post '/get-option', to: 'frontend#get_option', as: :get_option
  get 'centros-de-recargas/:municipality_permalink/:sector_permalink/:riffils_center_permalink', to: 'frontend#show_center', as: :show_center
  get 'rutas-de-transporte/:municipality_permalink/:sector_permalink/:road_transport_permalink', to: 'frontend#show_road', as: :show_road
  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  #contacts
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  #catalogo
  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'
end

app/models/user.rb
require 'elasticsearch/model'
class User < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink, on: :create
  before_validation :asign_rol, on: :create
  rolify
  validates_presence_of :name, :role_ids, :email, :identification, :password_confirmation

  has_many :orders
  #has_many :posts, dependent: :destroy relation posts
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def rol
    self.roles.first.name
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:rol, :name, :email, :id] , operator: :and }  }, sort: { id: "desc" }, size: User.count }
  end

  #saber la pagina a la que pertenece
  def page(order = :id)
    ((self.class.order(order => :desc).pluck(order).index(self.send(order))+1).to_f / self.class.default_per_page).ceil
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      email: self.email,
      name: self.name,
      rol: self.rol
    }.as_json
  end

  private

  def asign_rol
    if role_ids.empty?
      add_role :client
    end
  end

  def create_permalink
    self.permalink = self.name.downcase.parameterize+"-"+SecureRandom.hex(4)
  end

end

#User.import

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  layout :resolve_layout
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy, :update_user_edit]

  def index
    @term = Term.last
    users = User.searching(@query).where.not(id: current_user.id)
    @objects, @total = users.page(@current_page), users.size
    redirect_to users_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end
  
  def update
    respond_to do |format|
      update_attributes = user_params.delete_if do |attribute, value|
        case attribute
          when "password"
            value.blank?
          when "password_confirmation"
            value.blank? if user_params.fetch("password").blank?
        end
      end

      if @user.update_attributes(update_attributes)    
        if params.fetch(:commit).eql?("Asignar Rol")
          format.html { redirect_to users_path, :notice => "Rol asignado satisfactoriamente" }
        else
          format.html { redirect_to user_path(@user), :notice => "Usuario actualizado satisfactoriamente" }
        end
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end

    end
  end

  def edit_profile
    @user = current_user
  end

  def update_user_edit
    if @user.update_attributes(user_params)
      sign_in(@user, bypass: true)
      redirect_to edit_user_registration_path, notice: 'El Usuario Ha Sido Modificado con Éxito'
    else
      render 'devise/registrations/edit'
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.add_role Role.find(user_params.fetch(:role_ids)).name
        format.html { redirect_to user_path(@user), notice: "Usuario creado satisfactoriamente" }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: "Usuario eliminado satisfactoriamente" 
  end

  def destroy_multiple
    User.destroy redefine_ids(params[:multiple_ids])
    redirect_to users_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

def export
  @clients = User.all

  respond_to do |format|
    format.xlsx {
      render xlsx: 'export', filename: "#{Date.today.strftime('%Y%m%d')}_Clientes.xlsx"
    }
  end
end
  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name, :email, :usertype, :identification,
      :address, :phone1, :phone2, :contact, :password, 
      :password_confirmation, :role_ids, :encrypted_password,
      :type_rif, :fiscal_address, :state, :municipality
    )
  end

  def resolve_layout
    case action_name.to_sym
    when :update_user_edit, :edit_profile
      'frontend/application'
    else
      'admin/application'
    end
  end
end

app/views/users/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Módulo de usuarios
		%p Aquí podrá gestionar todos los usuarios del sistema, ofrece opciones para crear, editar, eliminar y visualizar, tambien tiene la opción de asignar roles para controlar el acceso de sus usuarios en la aplicación.

		= link_to "Exportar usuarios", export_user_path(format: :xlsx) 

app/views/users/_form.html.haml
.wrapper
  .wrapper-body.container
    .actions
      = link_to users_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
        = material_icon.md_18.arrow_back.css_class("md-dark")
    .wrapper-inputs
      .card
        = simple_form_for @user do |f|
          .row 
            = f.input :name
            = f.input :email
            = f.input :role_ids, collection: Role.where.not(name: "superadmin").map { |rol| [rol.name.humanize, rol.id] }, label: false, include_blank: "Selecione un rol"
            = f.input :password
            = f.input :password_confirmation
            .form-actions.right
              = f.button :submit, "Guardar", class: "btn"

app/views/users/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, User
			= link_to "#modal-#{@user.id}", class: "btn-floating waves-effect waves-light btn-flat tooltipped modal-trigger", "data-position" => "bottom", "data-tooltip" => "Cambiar rol"  do
				= material_icon.md_24.supervisor_account
		- if can? :update, User
			= link_to edit_user_path(@user), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		- @user.as_json(only: ["id", "name", "permalink", "email", "created_at", "sign_in_count", "updated_at", "password"]).each do |attribute, value|
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.#{attribute}")
				.display-value= value

= render "users/modal"

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/users/_juridica.html.haml
= f.input :name, label: "Nombre", autofocus: true, placeholder: "Nombre", input_html: { class: 'form-control' }, wrapper: false

= f.label "Rif"
.row
	.col-lg-2
		= f.input :type_rif, label: false, collection:['J', 'G'],autofocus: true, placeholder: 'RIF', input_html: { class: 'form-control input-register' }, wrapper: false, include_blank: false
	.col-lg-10
		= f.input :identification, label: false ,autofocus: true, placeholder: 'RIF', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :state, label: 'Estado', autofocus: true, placeholder: 'Estado', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :municipality, label: 'Municipio', autofocus: true, placeholder: 'Municipio', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :address, label: 'Dirección de Envío', autofocus: true, placeholder: 'Ejemplo: Estado - Municipio - Sector/Urb - AV./Calle/Manzana/Piso - Casa/Apartamento', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :fiscal_address, label: 'Dirección Fiscal', as: :text, autofocus: true, placeholder: 'Ejemplo: Estado - Municipio - Sector/Urb - AV./Calle/Manzana/Piso - Casa/Apartamento', input_html: { class: 'form-control input-register' }, wrapper: false


= f.input :phone1, label: "Telefono de Contacto 1", autofocus: true, placeholder: "Teléfono de Contacto 1", input_html: { class: 'form-control' }, wrapper: false

= f.input :phone2, label: "Telefono de Contacto 2", autofocus: true, placeholder: "Teléfono de Contacto 2", input_html: { class: 'form-control' }, wrapper: false

= f.input :email, label: "Correo", autofocus: true, placeholder: "Email", input_html: { class: 'form-control' }, wrapper: false

= f.input :contact, label: "Contacto", autofocus: true, placeholder: "Contacto", input_html: { class: 'form-control' }, wrapper: false

= f.input :password, label: "Contraseña", autofocus: true, placeholder: "Contraseña", input_html: { class: 'form-control' }, wrapper: false

= f.input :password_confirmation, label: "Confirmación de Contraseña", autofocus: true, placeholder: "Confirmación de Contraseña", input_html: { class: 'form-control' }, wrapper: false

= f.submit "Guardar", :class => 'btn-rs pull-right btn'

app/views/users/_listing.html.haml
%tr{ id: "row-#{user.id}" }
	- if can? :destroy_multiple, User
		%td.item-check{style:"width: 10%"}
			= link_to "", user_path(user), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{user.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{user.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{user.id}" }
	%td.hide-on-small-and-down{style:"width: 30%"}
		= link_to "", user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.name											
	%td{style:"width: 35%"}
		= link_to "", user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.email			 
	%td.hide-on-small-and-down{style:"width: 20%"}
		= link_to "", user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.rol.humanize
	%td{style:"width: 5%"}		
		= link_to user_path(user), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/users/_modal.html.haml
.modal{ id: "modal-#{@user.id}"}
	= form_tag user_path(@user),  method: "PUT" do
		.modal-header
			%h4= "Cambiar rol de #{@user.name}"
		.modal-content
			- Role.all.each do |role|
				.radio-button
					= radio_button_tag "user[role_ids]", role.id, false, class: "radio-button__input", id: "radio#{role.id}", :type => "radio", :value => "#{role.id}", :checked => @user.has_role?(role.name)
					= label_tag "user[role_ids]", role.name.humanize, class: "radio-button__label", :for => "radio#{role.id}"
		.modal-footer
			= button_tag "Asignar Rol", :class => "waves-effect waves-light btn", name: 'commit', value: "Asignar Rol"
			= link_to "Cancelar", "", class: "modal-action modal-close waves-effect waves-light btn red"
		

app/views/users/_natural.html.haml
= f.input :name, label: "Nombre" , autofocus: true, placeholder: "Nombre", input_html: { class: 'form-control input-register' }, wrapper: false

= f.label "Cedula de identidad"
.row
	.col-lg-2
		= f.input :type_rif, label: false, collection:['V', 'E'],autofocus: true, placeholder: 'Cedula', input_html: { class: 'form-control input-register' }, wrapper: false, include_blank: false
	.col-lg-10
		= f.input :identification, label: false ,autofocus: true, placeholder: 'Cedula', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :state, label: 'Estado', autofocus: true, placeholder: 'Estado', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :municipality, label: 'Municipio', autofocus: true, placeholder: 'Municipio', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :address, label: 'Dirección de Envío', autofocus: true, placeholder: 'Ejemplo: Estado - Municipio - Sector/Urb - AV./Calle/Manzana/Piso - Casa/Apartamento', input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :phone1, label: "Teléfono de Contacto 1", autofocus: true, placeholder: "Teléfono de Contacto 1", input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :phone2, label: "Teléfono de Contacto 2", autofocus: true, placeholder: "Teléfono de Contacto 2", input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :email, label: "Email", autofocus: true, placeholder: "Email", input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :password, label: "Contraseña", autofocus: true, placeholder: "Contraseña", input_html: { class: 'form-control input-register' }, wrapper: false

= f.input :password_confirmation, label: "Confirmación de Contraseña", autofocus: true, placeholder: "Confirmación de Contraseña", input_html: { class: 'form-control input-register' }, wrapper: false

= f.submit "Guardar", :class => 'btn-rs pull-right btn'

app/views/users/edit.html.haml
= title "Usuarios - editar | #{@user.name}"
= render 'form'

app/views/users/edit_profile.html.haml
.container
  .flex-parent
    .flex-item
      .title-app.text-center
        Editar 
      = simple_form_for(@user, :as => resource_name, :url => update_user_edit_path(@user), :method => :PUT, wrapper: :bootstrap) do |f|
        .content
          = devise_error_messages!
          .body-form
            = f.input :usertype, label: "Tipo de Cliente", collection: ["Jurídico", "Natural"], include_blank: "Tipo de Cliente", autofocus: true, input_html: { class: 'form-control input-register' , id: "select-register"}
            #juridica_form
              = render "users/juridica", f:f
            #natural_form
              = render "users/natural", f:f


          - if @user.type_rif.eql?("J") || @user.type_rif.eql?("G")
            :javascript
              $("#juridica_form").show();
              $("#natural_form").hide();
          -else
            :javascript
              $("#juridica_form").hide();
              $("#natural_form").show();

          :javascript
            $( "#select-register" )
              .change(function () {
                var str = "";
                $( "#select-register option:selected" ).each(function() {
                  str += $( this ).text();
                });
                if (str == "Jurídico"){
                 $("#juridica_form").show(); 
                 $("#natural_form").hide();
                }
                if (str == "Natural"){
                 $("#natural_form").show();
                 $("#juridica_form").hide();
                }
              })
            .change();

app/views/users/index.html.haml
//change title
= title("Usuario - Listado")

.listing.col.l9.m12.s12
	= link_to new_user_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
		= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |user|
				= render 'listing', user: user
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado usuarios.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"
	


= link_to new_user_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
	= material_icon.md_24.add.css_class("md-light")

app/views/users/new.html.haml
= title "Usuarios - Nuevo"
= render 'form'

app/views/users/show.html.haml
= title "Usuarios | #{@user.name}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, User
				= link_to user_path(@user), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, User
				= link_to edit_user_path(@user), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to users_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				- @user.as_json(only: ["id", "name", "permalink", "email","created_at", "sign_in_count", "updated_at", "password"], methods: [:rol]).each do |attribute, value|
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.#{attribute}")
						.display-value.fs-body-1.tc-black-2= value.to_s.humanize

app/views/users/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@user.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");