config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, controllers: {registrations: 'registrations'}, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index
  
  scope :admin do

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :payments do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :road_transports do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end

    resources :municipalities do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :sectors do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :terms do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :riffils_centers do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end
    
  end

  #ajax galeria
  get '/option-landing-gallery/:option', to: 'frontend#option_landing_gallery', as: :option_landing_gallery
  get '/option-show-gallery/:option', to: 'frontend#option_show_gallery', as: :option_show_gallery


  #galeria show
  get '/gallery/:option', to: 'frontend#show_gallery', as: :show_gallery

  #orders
  get '/ordenes', to: 'orders#view_orders', as: :view_orders
  post '/ordenes/new_order', to: 'orders#create_orders', as: :create_orders

  #orders edit status admin
  put '/ordenes/change_status/:id', to: 'orders#change_status', as: :change_status

  #mail
  get '/ordenes/send_receipt/:id', to: 'orders#send_receipt', as: :send_receipt

  #Mercado_Pago
  get '/ordenes/success', to: 'mercado_pago#success', as: :success
  get '/ordenes/failure', to: 'mercado_pago#failure', as: :failure
  post '/ordenes/hook', to: 'mercado_pago#hook', as: :hook

  #validar mercado pago ordenes
  get '/validate_payment/:id', to: 'orders#validate_payment', as: :validate_payment

  #user edit
  get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
  put '/users/update_user_edit/:id', to: 'users#update_user_edit', as: :update_user_edit

  #export user
  get '/export/user', to: 'users#export', as: :export_user

  get '/get-sectors/:opcion/:municipality_id', to: 'frontend#get_sectors', as: :get_sectors
  get '/get-center/:opcion/:center_id', to: 'frontend#get_center', as: :get_road
  post '/get-option', to: 'frontend#get_option', as: :get_option
  get 'centros-de-recargas/:municipality_permalink/:sector_permalink/:riffils_center_permalink', to: 'frontend#show_center', as: :show_center
  get 'rutas-de-transporte/:municipality_permalink/:sector_permalink/:road_transport_permalink', to: 'frontend#show_road', as: :show_road
  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  #contacts
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  #catalogo
  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  layout 'layouts/frontend/application'
  before_filter :selector, only: [:get_sectors, :get_center]
  before_filter :form_message

  def index
    @posts = KepplerBlog::Post.where(public: true).last(4)
    @municipality = Municipality.all.order('name ASC')
    @catalog_fotos = KepplerCatalogs::Catalog.find_by_section('Galeria')
    @catalog = KepplerCatalogs::Catalog.find_by_name('FOTOS')
    @attachments = @catalog_fotos.attachments.where(public: true).last(4) if @catalog_fotos
  end

  def option_landing_gallery
    @catalog = KepplerCatalogs::Catalog.find_by_name(params[:option])
    @attachments = @catalog.attachments.where(public: true).last(4)
  end

  def show_gallery
    @catalog = KepplerCatalogs::Catalog.find_by_name(params[:option])
    @attachments = @catalog.attachments.where(public: true).order(created_at: :desc)
    @attachments = @attachments.page(params[:page]).per(16)
  end

  def option_show_gallery
    show_gallery
  end

  def get_sectors
    @municipality = Municipality.find(params[:municipality_id])
    respond_to do |format|
      format.js {}
    end
  end

  def get_center
    @sector = Sector.find(params[:center_id])
    respond_to do |format|
      format.js {}
    end
  end

  def get_option
    case params[:commit]
    when 'center'
      @nunicipality = Municipality.find(params[:municipality])
      @sector = Sector.find(params[:sector])
      @riffils_center = RiffilsCenter.find(params[:center])
      redirect_to show_center_path(@nunicipality.permalink, @sector.permalink, @riffils_center.permalink, :anchor => "anchor")
    when 'road'
      @nunicipality = Municipality.find(params[:municipality])
      @sector = Sector.find(params[:sector])
      @road_transport = RoadTransport.find(params[:road])
      redirect_to show_road_path(@nunicipality.permalink, @sector.permalink, @road_transport.permalink, :anchor => "anchor")
    end
  end

  def show_center
    @municipality = Municipality.all
    @municipality_load = Municipality.find_by_permalink(params[:municipality_permalink])
    @sector = Sector.find_by_permalink(params[:sector_permalink])
    @riffils_center = RiffilsCenter.find_by_permalink(params[:riffils_center_permalink])
  end

  def show_road
    @municipality = Municipality.all
    @municipality_load = Municipality.find_by_permalink(params[:municipality_permalink])
    @sector = Sector.find_by_permalink(params[:sector_permalink])
    @road_transport = RoadTransport.find_by_permalink(params[:road_transport_permalink])
  end


  private

  def form_message
    @message = KepplerContactUs::Message.new
  end

  def selector
    @selector = case params[:opcion]
    when "center"
      "center"
    when "road"
      "road"
    end
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
  def header_section(title, subtitle)
    content_tag :div, class: "header-section" do
      content_tag(:div, title, class: "title-section")+
      content_tag(:div, image_tag("frontend/points.png"), class: "image-section")+
      content_tag(:div, subtitle,  class: "subtitle-section")
    end
  end

  def buttons_gallery_section(option, position)
    content_tag :div, class: "col-lg-6 col-xs-6 no-padding" do
      content_tag(
        :button, "#{option}",
        class: "btn btn-option-gallery pull-#{position}",
        id: "option-#{option.downcase}"
      )
    end
  end

  def root_path?
    controller_name.eql? "frontend" and action_name.eql? "index"
  end

  def show_blog?
    controller_name.eql? "blog" and action_name.eql? "show"
  end

  def listing_blog?
    controller_name.eql? "blog" and action_name.eql? "index"
  end

  def show_center?
    controller_name.eql? "frontend" and action_name.eql? "show_center"
  end

  def show_road?
    controller_name.eql? "frontend" and action_name.eql? "show_road"
  end

  def frontend_index?
    controller_name.eql?('frontend') && action_name.eql?('index')
  end

  def sign_in?
    controller_name.eql?('sessions') && action_name.eql?('new')
  end

  def option_landing_gallery?
    controller_name.eql?('frontend') && action_name.eql?('option_landing_gallery')
  end
end

app/views/frontend/pages/_about.html.haml
.container
	.header-section
		.title-section
			TRANSFALCÓN
		.subtitle-section
			LA REVOLUCIÓN DEL TRANSPORTE
	.row.about-section
		.col-lg-6.mision
			.title-section
				MISIÓN
			.about-content
				Garantizar que el servicio público de transporte terrestre de pasajeros se ejecute con los mayores estándares de calidad en todos los sectores rurales, urbanos, suburbanos e interurbanos del estado, así como el apoyo a organismos públicos a través de unidades de alta tecnología con un personal competente, adiestrado y comprometido con los objetivos institucionales, asegurando el crecimiento social, cultural y económico del estado Falcón.
		.col-lg-6.vision
			.title-section
				VISIÓN
			.about-content
				Ser empresa líder ejemplo de eficiencia, eficacia y calidad en el servicio público de transporte terrestre de pasajeros en el estado Falcón o cualquier territorio de la República Bolivariana de Venezuela, con el reconocimiento de nuestros usuarios por la excelencia en los niveles de seguridad y capacidad de servicio ofrecidos a toda la población.
.container.about-organigrama
	.row
		.col-lg-12
			.header-section
				.title-section
					CONOCE CÓMO ESTAMOS CONFORMADOS
			.btn.btn-section{ "data-toggle" => "modal", "data-target" => "#organization-modal" }
				ORGANIGRAMA			

#organization-modal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog{:role => "document"}
		.modal-content
			.modal-body
				= image_tag "frontend/bg-modal-new.png", class: "hidden-xs hidden-sm"
				= image_tag "frontend/bg-modal-responsive-new.png", class: "visible-xs visible-sm"
			.modal-footer
				%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cerrar

app/views/frontend/pages/_attachments.html.haml
- if @attachments
  - @attachments.each do |attachment|
    - if attachment.image?
      .col-lg-3.col-md-6.col-sm-6.col-xs-12.grid-item.hvr-shrink
        %a{"data-toggle" => "modal", "data-target" => "#modal-#{attachment.id}", type: "button", href: "#"}
          .mask
            %span 
              = attachment.name
          .item-img
            = image_tag attachment.image, class: "img-responsive", style: "height: 220px;"
      .modal-image.modal.fade{id: "modal-#{attachment.id}", "aria-labelledby" => "gridSystemModalLabel", :role => "dialog", :tabindex => "-1"}
        .modal-dialog{:role => "document"}
          .modal-content
            .modal-body
              .row
                .col-xs-12.col-sm-12.col-md-12.col-lg-12
                  = image_tag attachment.image
                

    - elsif attachment.url? and attachment.upload.eql?("3")
      .col-lg-3.col-md-6.col-sm-6.col-xs-12.grid-item.hvr-shrink
        %a{"data-toggle" => "modal", type: "button", href:"#modal-#{attachment.id}"}
          .mask
            %span
              %i.fa.fa-youtube-play.fa-3x{"aria-hidden" => "true"}
          .item-img
          = image_tag(attachment.thumbnail_youtube, class: "img-responsive img-rounded img-gallery hvr-grow", style: "height: 220px;")
      .modal.fade{id: "modal-#{attachment.id}", :role => "dialog", :tabindex => "-1"}
        .modal-dialog
          .modal-content
            .modal-body
              .row
                .col-xs-12.col-sm-12.col-md-12.col-lg-12
                  %iframe.video-player{id: "#video-#{attachment.id}", allowfullscreen: "", frameborder: "1", height: "350"}
                  :javascript
                    $(document).ready(function(){
                      var url = "#{attachment.url}";
                      var autoplay = "?autoplay=1";
                      
                      $("iframe #video-#{attachment.id}").attr('src', '');
                    
                      $("#modal-#{attachment.id}").on('shown.bs.modal', function(){
                          $("#modal-#{attachment.id} iframe").attr('src', url + autoplay);
                      });
                      
                      $("#modal-#{attachment.id}").on('hide.bs.modal', function(){
                          $("iframe").attr('src', "");
                      });
                    });

- if frontend_index? || option_landing_gallery? && @catalog 
  .col-lg-12.col-xs-12{style:"padding: 0;"}
    %center
      = link_to show_gallery_path(@catalog.name.downcase), class: "btn btn-option-gallery", id: "option-show-gallery-#{@catalog.name}" do
        VER MÁS
- else 
  .container
    .row
      .col-md-12.text-center
        = paginate @attachments

app/views/frontend/pages/_gallery.html.haml
.row.container-fluid.padng-top#parcial-gallery
	= header_section("GALERíA", "")
	= render "frontend/pages/attachments"

app/views/frontend/pages/_home.html.haml
.content
  %h1.title TRANSFALCÓN
  %h3.subtitle 
    SE MUEVE CON LA GENTE
    = image_tag "frontend/points.png"

  .banner-buy-card
    %p.banner-buy-card-text ADQUIERE TU SISTEMA ÚNICO DE PAGO
    - if user_signed_in?
      - if current_user.rol.eql?('admin') || current_user.rol.eql?('superadmin')
        = link_to("Ver Pedidos", orders_path, class: "btn btn-send-mailer")
      -else
        = link_to("Ver Mis Ordenes", view_orders_path, class: "btn btn-send-mailer")
    - else
      = link_to("COMPRA TU TARJETA", new_user_session_path , class: "btn btn-send-mailer")

app/views/frontend/pages/_how.html.haml
.container
	= header_section("¿CÓMO FUNCIONA NUESTRO SERVICIO?", "Con Transfalcón es muy fácil llegar a tu destino, conoce nuestro moderno y seguro sistema de transporte urbano y suburbano.")
	.container.how-section
		.row
			- (1..3).each do |index|
				.col-lg-4
					.how-section-content
						.how-section-content-link
							.how-section-content-image
								= image_tag "frontend/how-#{index}.png"
							.how-section-content-text
								= t("frontend.how.text-#{index}")

app/views/frontend/pages/_navigation_btn_sign.html.haml
.config-wrapper
  .config-wrapper-inner
    %a.config-trigger{id: "config-trigger"}
      %i.fa.fa-user.fa-2x
    .config-panel.display{id: "config-panel"}
      - if user_signed_in?
        - if is_index?
          - if current_user.rol.eql?('admin') || current_user.rol.eql?('superadmin')
            = link_to("Ver Pedidos", orders_path, class: "btn btn-send-mailer")
            
            = link_to("Administración", admin_index_path, class: "btn btn-send-mailer")
            
            = link_to("Cerrar Sesión", destroy_user_session_path, class: "btn btn-send-mailer")
          - else
            = link_to("Ver Mis Ordenes", view_orders_path, class: "btn btn-send-mailer")
            
            = link_to("Editar Perfil", edit_profile_path, class: "btn btn-send-mailer")
            
            = link_to("Cerrar Sesión", destroy_user_session_path, class: "btn btn-send-mailer")
        - else
          - if current_user.rol.eql?('admin') || current_user.rol.eql?('superadmin')
            = link_to("Ver Mis Ordenes", view_orders_path, class: "btn btn-send-mailer")
            
            = link_to("Administración", admin_index_path, class: "btn btn-send-mailer")
            
            = link_to("Cerrar Sesión", destroy_user_session_path, class: "btn btn-send-mailer")
          - else
            = link_to("Ver Mis Ordenes", view_orders_path, class: "btn btn-send-mailer")
            
            = link_to("Editar Perfil", edit_profile_path, class: "btn btn-send-mailer")
            
            = link_to("Cerrar Sesión", destroy_user_session_path, class: "btn btn-send-mailer")
      - else
        
        = link_to("Iniciar Sesión", new_user_session_path, class: "btn btn-send-mailer")
        
        = link_to("Registrarse", new_user_registration_path, class: "btn btn-send-mailer")
:javascript
  var toggle = 0
  $('#config-trigger').on('click', function(e) {
    if(toggle==0){
      $('.config-wrapper').animate({
        right:"0px"
      })
      toggle = 1;
    }else{
      $('.config-wrapper').animate({
        right: "-200px"
      })
      toggle = 0;
    }
  });
    
    $('#config-close').on('click', function(e) {
        e.preventDefault();
        $('#config-panel').hide();
    });

app/views/frontend/pages/_news.html.haml
.banner
	.row{style:"width: 100%; margin: 0px;"}
		.col-lg-6{style:"padding: 0px;"}
			= image_tag "frontend/logo-ministerio.jpg", class: "pull-left", id: "logo-ministerio"
		
		.col-lg-6
			= image_tag "frontend/gobernacion.png", class: "pull-right", id: "logo-gobernacion", width:"42%"

- unless @posts.empty?
	.container
		.row.posts.hidden-xs
			.post.col-lg-6
				= link_to "blog/#{@posts[3].permalink}" do
					.post-image{ style: "background-image: url(#{@posts[3].image}); height: 400px;" }
						.post-title
							%p #{@posts[3].title}
							%p.link-blog VER MAS

			.post.col-lg-6
				= link_to "blog/#{@posts[2].permalink}" do
					.post-image-2{ style: "background-image: url(#{@posts[2].image}); height: 200px;" }
						.post-title
							%p #{@posts[2].title}
							%p.link-blog VER MAS
				.post.col-lg-6
					= link_to "blog/#{@posts[1].permalink}" do
						.post-image-3{ style: "background-image: url(#{@posts[1].image}); height: 200px;" }
							.post-title
								%p #{@posts[1].title}
								%p.link-blog VER MAS
				.post.col-lg-6
					= link_to "blog/#{@posts[0].permalink}" do
						.post-image-4{ style: "background-image: url(#{@posts[0].image}); height: 200px;" }
							.post-title
								%p #{@posts[0].title}
								%p.link-blog VER MAS

		.row.posts.hidden-lg.hidden-md.hidden-sm
			.post.col-xs-12{ style: "height: 350px;"}
				= link_to "blog/#{@posts[0].permalink}" do
					.post-image{ style: "background-image: url(#{@posts[0].image}); height: 350px;" }
						.post-title
							%p #{@posts[0].title}
							%p.link-blog VER MAS
			.post.col-xs-12{ style: "height: 350px;"}
				= link_to "blog/#{@posts[1].permalink}" do
					.post-image{ style: "background-image: url(#{@posts[1].image}); height: 350px;" }
						.post-title
							%p #{@posts[1].title}
							%p.link-blog VER MAS
			.post.col-xs-12{ style: "height: 350px;"}
				= link_to "blog/#{@posts[2].permalink}" do
					.post-image{ style: "background-image: url(#{@posts[2].image}); height: 350px;" }
						.post-title
							%p #{@posts[2].title}
							%p.link-blog VER MAS
			.post.col-xs-12{ style: "height: 350px;"}
				= link_to "blog/#{@posts[3].permalink}" do
					.post-image{ style: "background-image: url(#{@posts[3].image}); height: 350px;" }
						.post-title
							%p #{@posts[3].title}
							%p.link-blog VER MAS

app/views/frontend/pages/_refills_center.html.haml
.container
	= header_section("NUESTROS COMERCIOS ALIADOS", "Encuentra el centro de recarga más cercano para mantenerte en movimiento.")

	= form_tag get_option_path, class: "form-inline form-inline-default" do
		.col-lg-3
			= select_tag "municipality", options_from_collection_for_select(@municipality, :id, :name), include_blank: "Municipios", class: "form-control", id: "riffils_center_municipality_select"
		.col-lg-3
			= select_tag "sector", options_from_collection_for_select([], :id, :name), include_blank: "Sectores", class: "form-control", id: "riffils_center_sector_select", disabled: true
		.col-lg-3
			= select_tag "center", options_from_collection_for_select([], :id, :name), include_blank: "Centros de recarga", class: "form-control", id: "riffils_center_sector_center", disabled: true
		.col-lg-3
			%button{:name => "commit", class: "btn btn-send", id: "btn-center", disabled: true, :type => "submit", :value => "center"} VER INFORMACIÓN

app/views/frontend/pages/_road_transports.html.haml
.container
	= header_section("RUTAS TRANSFALCÓN", "Descubre hasta donde llega nuestro servicio de primera")
			
	= form_tag get_option_path, class: "form-inline form-inline-default" do
		.col-lg-3
			= select_tag "municipality", options_from_collection_for_select(@municipality, :id, :name), include_blank: "Municipios", class: "form-control", id: "riffils_center_municipality_select2"
		.col-lg-3
			= select_tag "sector", options_from_collection_for_select([], :id, :name), include_blank: "Sectores", class: "form-control", id: "riffils_center_sector_select2", disabled: true
		.col-lg-3
			= select_tag "road", options_from_collection_for_select([], :id, :name), include_blank: "Rutas", class: "form-control", id: "riffils_center_sector_road", disabled: true
		.col-lg-3
			%button{:name => "commit", class: "btn btn-send", id: "btn-road", disabled: true, :type => "submit", :value => "road"} VER INFORMACIÓN