config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, controllers: {registrations: 'registrations'}, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index
  
  scope :admin do

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :payments do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :road_transports do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end

    resources :municipalities do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :sectors do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :terms do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :riffils_centers do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end
    
  end

  #ajax galeria
  get '/option-landing-gallery/:option', to: 'frontend#option_landing_gallery', as: :option_landing_gallery
  get '/option-show-gallery/:option', to: 'frontend#option_show_gallery', as: :option_show_gallery


  #galeria show
  get '/gallery/:option', to: 'frontend#show_gallery', as: :show_gallery

  #orders
  get '/ordenes', to: 'orders#view_orders', as: :view_orders
  post '/ordenes/new_order', to: 'orders#create_orders', as: :create_orders

  #orders edit status admin
  put '/ordenes/change_status/:id', to: 'orders#change_status', as: :change_status

  #mail
  get '/ordenes/send_receipt/:id', to: 'orders#send_receipt', as: :send_receipt

  #Mercado_Pago
  get '/ordenes/success', to: 'mercado_pago#success', as: :success
  get '/ordenes/failure', to: 'mercado_pago#failure', as: :failure
  post '/ordenes/hook', to: 'mercado_pago#hook', as: :hook

  #validar mercado pago ordenes
  get '/validate_payment/:id', to: 'orders#validate_payment', as: :validate_payment

  #user edit
  get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
  put '/users/update_user_edit/:id', to: 'users#update_user_edit', as: :update_user_edit

  #export user
  get '/export/user', to: 'users#export', as: :export_user

  get '/get-sectors/:opcion/:municipality_id', to: 'frontend#get_sectors', as: :get_sectors
  get '/get-center/:opcion/:center_id', to: 'frontend#get_center', as: :get_road
  post '/get-option', to: 'frontend#get_option', as: :get_option
  get 'centros-de-recargas/:municipality_permalink/:sector_permalink/:riffils_center_permalink', to: 'frontend#show_center', as: :show_center
  get 'rutas-de-transporte/:municipality_permalink/:sector_permalink/:road_transport_permalink', to: 'frontend#show_road', as: :show_road
  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  #contacts
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  #catalogo
  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'
end

app/models/payment.rb
#Generado por keppler
require 'elasticsearch/model'
class Payment < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :order, inverse_of: :payment

  validates_presence_of :type_payment
  validates_presence_of :transfer_bank, if: :transfer?
  validates_presence_of :transfer_code, if: :transfer?

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end

  def transfer?
    type_payment.eql?('Transferencia Bancaria')
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      mp_code:  self.mp_code.to_s,
      transfer_code:  self.transfer_code.to_s,
      transfer_date:  self.transfer_date,
      transfer_bank:  self.transfer_bank.to_s,
      order:  self.order.to_s,
    }.as_json
  end

end
#Payment.import

app/controllers/payments_controller.rb
#Generado con Keppler.
class PaymentsController < ApplicationController  
  before_filter :authenticate_user!
  layout :resolve_layout
  load_and_authorize_resource
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  def index
    payments = Payment.searching(@query).all
    @objects, @total = payments.page(@current_page), payments.size
    redirect_to payments_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /payments/1
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      redirect_to @payment, notice: 'Payment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /payments/1
  def update
    if @payment.update(payment_params)
      redirect_to @payment, notice: 'Payment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /payments/1
  def destroy
    @payment.destroy
    redirect_to payments_url, notice: 'Payment was successfully destroyed.'
  end

  def destroy_multiple
    Payment.destroy redefine_ids(params[:multiple_ids])
    redirect_to payments_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def payment_params
      params.require(:payment).permit(:mp_code, :transfer_code, :transfer_date, :transfer_account, :transfer_bank, :type_payment)
    end

    def resolve_layout
    case action_name.to_sym
    when :update_user_edit, :edit_profile
      'frontend/application'
    else
      'admin/application'
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/payments/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to payments_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @payment do |f|
					.row
						= f.input :mp_code
						= f.input :transfer_code
						= f.input :transfer_date, as: :string, input_html: {class: "datepicker"}
						= f.input :transfer_bank
						= f.association :order

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/payments/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Payment
			= link_to edit_payment_path(@payment), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @payment.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.mp_code")
			.display-value= @payment.mp_code
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.transfer_code")
			.display-value= @payment.transfer_code
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.transfer_date")
			.display-value= @payment.transfer_date
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.transfer_bank")
			.display-value= @payment.transfer_bank
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.order")
			.display-value= @payment.order
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/payments/_listing.html.haml
%tr{ id: "row-#{payment.id}" }
	- if can? :destroy_multiple, Payment
		%td.item-check{style:"width: 10%"}
			= link_to "", payment_path(payment), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{payment.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{payment.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{payment.id}" }

		%td{style:"width: 30%"}
			= link_to "", payment_path(payment, search: @query), remote: true, class: "show-row"
			%span
				= payment.mp_code
		%td{style:"width: 30%"}
			= link_to "", payment_path(payment, search: @query), remote: true, class: "show-row"
			%span
				= payment.transfer_code
		%td{style:"width: 30%"}
			= link_to "", payment_path(payment, search: @query), remote: true, class: "show-row"
			%span
				= payment.transfer_date
		%td{style:"width: 30%"}
			= link_to "", payment_path(payment, search: @query), remote: true, class: "show-row"
			%span
				= payment.transfer_bank
		%td{style:"width: 30%"}
			= link_to "", payment_path(payment, search: @query), remote: true, class: "show-row"
			%span
				= payment.order
								
	%td{style:"width: 5%"}		
		= link_to payment_path(payment), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/payments/edit.html.haml
= title "Payments - editar | #{@payment.id}"
= render 'form'

app/views/payments/index.html.haml
= title("Payments - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_payment_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |payment|
				= render 'listing', payment: payment
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado payments.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_payment_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/payments/new.html.haml
= title "Payments - Nuevo"
= render 'form'

app/views/payments/show.html.haml
= title "Payments | #{@payment.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Payment
				= link_to payment_path(@payment), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Payment
				= link_to edit_payment_path(@payment), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to payments_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @payment.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.mp_code")
					.display-value.fs-body-1.tc-black-2= @payment.mp_code.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.transfer_code")
					.display-value.fs-body-1.tc-black-2= @payment.transfer_code.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.transfer_date")
					.display-value.fs-body-1.tc-black-2= @payment.transfer_date.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.transfer_bank")
					.display-value.fs-body-1.tc-black-2= @payment.transfer_bank.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.order")
					.display-value.fs-body-1.tc-black-2= @payment.order.to_s.humanize

app/views/payments/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@payment.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");