config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, controllers: {registrations: 'registrations'}, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index
  
  scope :admin do

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :payments do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :orders do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :road_transports do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end

    resources :municipalities do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :sectors do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :terms do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :riffils_centers do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      get ":municipality_id/sectors", action: :sectors_of_municipality, on: :collection, as: :sectors_of_municipality
    end
    
  end

  #ajax galeria
  get '/option-landing-gallery/:option', to: 'frontend#option_landing_gallery', as: :option_landing_gallery
  get '/option-show-gallery/:option', to: 'frontend#option_show_gallery', as: :option_show_gallery


  #galeria show
  get '/gallery/:option', to: 'frontend#show_gallery', as: :show_gallery

  #orders
  get '/ordenes', to: 'orders#view_orders', as: :view_orders
  post '/ordenes/new_order', to: 'orders#create_orders', as: :create_orders

  #orders edit status admin
  put '/ordenes/change_status/:id', to: 'orders#change_status', as: :change_status

  #mail
  get '/ordenes/send_receipt/:id', to: 'orders#send_receipt', as: :send_receipt

  #Mercado_Pago
  get '/ordenes/success', to: 'mercado_pago#success', as: :success
  get '/ordenes/failure', to: 'mercado_pago#failure', as: :failure
  post '/ordenes/hook', to: 'mercado_pago#hook', as: :hook

  #validar mercado pago ordenes
  get '/validate_payment/:id', to: 'orders#validate_payment', as: :validate_payment

  #user edit
  get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
  put '/users/update_user_edit/:id', to: 'users#update_user_edit', as: :update_user_edit

  #export user
  get '/export/user', to: 'users#export', as: :export_user

  get '/get-sectors/:opcion/:municipality_id', to: 'frontend#get_sectors', as: :get_sectors
  get '/get-center/:opcion/:center_id', to: 'frontend#get_center', as: :get_road
  post '/get-option', to: 'frontend#get_option', as: :get_option
  get 'centros-de-recargas/:municipality_permalink/:sector_permalink/:riffils_center_permalink', to: 'frontend#show_center', as: :show_center
  get 'rutas-de-transporte/:municipality_permalink/:sector_permalink/:road_transport_permalink', to: 'frontend#show_road', as: :show_road
  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  #contacts
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  #catalogo
  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'
end

app/models/municipality.rb
#Generado por keppler
require 'elasticsearch/model'
class Municipality < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink, on: :create
  has_many :road_transports
  has_many :sectors, :dependent => :destroy
  has_many :riffils_centers
  
  after_commit on: [:update] do
    __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order('name ASC')
    else
      self.order('name ASC')
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :name] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name,
      permalink:  self.permalink,
    }.as_json
  end

  private

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

end

app/controllers/municipalities_controller.rb
#Generado con Keppler.
class MunicipalitiesController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_municipality, only: [:show, :edit, :update, :destroy]

  # GET /municipalities
  def index
    municipalities = Municipality.searching(@query).all
    @objects, @total = municipalities.page(@current_page), municipalities.size
    redirect_to municipalities_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /municipalities/1
  def show
  end

  # GET /municipalities/new
  def new
    @municipality = Municipality.new
  end

  # GET /municipalities/1/edit
  def edit
  end

  # POST /municipalities
  def create
    @municipality = Municipality.new(municipality_params)

    if @municipality.save
      redirect_to @municipality, notice: 'Municipality was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /municipalities/1
  def update
    if @municipality.update(municipality_params)
      redirect_to @municipality, notice: 'Municipality was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /municipalities/1
  def destroy
    @municipality.destroy
    redirect_to municipalities_url, notice: 'Municipality was successfully destroyed.'
  end

  def destroy_multiple
    Municipality.destroy redefine_ids(params[:multiple_ids])
    redirect_to municipalities_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def municipality_params
      params.require(:municipality).permit(:name)
    end
end

app/views/municipalities/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_balance.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Permite agregar, mostrar, editar y eliminar municipios que pertenecen al conjunto de rutas de transporte y centros de recarga..

app/views/municipalities/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to municipalities_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @municipality do |f|
					.row
						= f.input :name

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/municipalities/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Municipality
			= link_to edit_municipality_path(@municipality), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_balance.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("Identificador")
			.display-value= @municipality.id
		%li.list-row
			.display-label= t("Nombre")
			.display-value= @municipality.name
		- unless @municipality.sectors.empty?
			%li.list-row
				.display-label Sectores
				.display-value
					%ul
						- @municipality.sectors.each do |sector|
							%li
								= "- #{sector.name}"
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/municipalities/_listing.html.haml
%tr{ id: "row-#{municipality.id}" }
	- if can? :destroy_multiple, municipality
		%td.item-check{style:"width: 10%"}
			= link_to "", municipality_path(municipality), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{municipality.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{municipality.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{municipality.id}" }

	%td{style:"width: 30%"}
		= link_to "", municipality_path(municipality, search: @query), remote: true, class: "show-row"
		%span
			= municipality.name
								
	%td{style:"width: 5%"}		
		= link_to municipality_path(municipality), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/municipalities/edit.html.haml
= title "Municipios - editar | #{@municipality.id}"
= render 'form'

app/views/municipalities/index.html.haml
= title("Municipios - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_municipality_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |municipality|
				= render 'listing', municipality: municipality
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado municipios.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_municipality_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/municipalities/new.html.haml
= title "Municipios - Nuevo"
= render 'form'

app/views/municipalities/show.html.haml
= title "Municipios | #{@municipality.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Municipality
				= link_to municipality_path(@municipality), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Municipality
				= link_to edit_municipality_path(@municipality), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to municipalities_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("Identificador")
					.display-value.fs-body-1.tc-black-2= @municipality.id
				%li.list-row
					.display-label= t("Nombre")
					.display-value.fs-body-1.tc-black-2= @municipality.name

				- unless @municipality.sectors.empty?
					%li.list-row
						.display-label Sectores
						.display-value
							%ul
								- @municipality.sectors.each do |sector|
									%li
										= "- #{sector.name}"

app/views/municipalities/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@municipality.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");